### ISSUE TITLE
cannot run expo web

### ISSUE THREAD

**Issue by edward1986** [itenl/react-native-scrollable-tabview-example-tiktok#1]
cannot run expo web, 
index.js:1 ./node_modules/@itenl/react-native-scrollable-tabview/src/index.js 27:19
Module parse failed: Unexpected token (27:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class ScrollableTabView extends React.Component {
>   static propTypes = {
|     stacks: PropTypes.array.isRequired,
|     firstIndex: PropTypes.number,

**Comment by itenl** [comment]
Use `npm run start` to test it, the way of compiling is different, and the component does not support the Web(`npm run web`) mode.
